"""Data access for driver profiles. SQLAlchemy only — no business rules."""
from __future__ import annotations

import uuid
from datetime import datetime

from geoalchemy2 import Geography
from geoalchemy2.elements import WKTElement
from sqlalchemy import cast, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.driver import Driver, DriverStatus


class DriverRepository:
    def __init__(self, db: AsyncSession) -> None:
        self.db = db

    async def get_by_id(self, driver_id: uuid.UUID) -> Driver | None:
        return await self.db.get(Driver, driver_id)

    async def get_by_user_id(self, user_id: uuid.UUID) -> Driver | None:
        result = await self.db.execute(
            select(Driver).where(Driver.user_id == user_id)
        )
        return result.scalar_one_or_none()

    async def create(
        self,
        *,
        user_id: uuid.UUID,
        vehicle_make: str,
        vehicle_model: str,
        vehicle_plate: str,
        vehicle_color: str | None,
    ) -> Driver:
        driver = Driver(
            user_id=user_id,
            vehicle_make=vehicle_make,
            vehicle_model=vehicle_model,
            vehicle_plate=vehicle_plate,
            vehicle_color=vehicle_color,
            status=DriverStatus.offline,
        )
        self.db.add(driver)
        await self.db.flush()
        await self.db.refresh(driver)
        return driver

    async def set_status(self, driver: Driver, status: DriverStatus) -> Driver:
        driver.status = status
        await self.db.flush()
        return driver

    async def find_nearest_available_driver(
        self,
        *,
        lat: float,
        lng: float,
        radius_m: int,
        zones: list[str] | None = None,
    ) -> Driver | None:
        """Nearest ONLINE driver within `radius_m` metres of (lat, lng).

        Two index-backed filters combine here:
          1. Geohash pre-filter: `geohash_zone = ANY(zones)` uses the btree index
             `ix_drivers_geohash_zone` to cheaply shrink the candidate set to the
             pickup cell + its 8 neighbours before any geometry math runs.
          2. Spatial filter/sort: ST_DWithin + ST_Distance use the GiST index
             `idx_drivers_location` on the geography column for the precise
             radius test and nearest ordering.

        Real EXPLAIN (ANALYZE, BUFFERS) with 5,000 online drivers seeded across
        a city (PostGIS 3.3, generated by scripts/explain_matching.py) — backs
        the "sub-100ms driver matching" claim:

            Limit  (actual time=5.827..5.829 rows=1 loops=1)
              ->  Sort  (Sort Key: st_distance(location, $point))
                    ->  Bitmap Heap Scan on drivers  (rows=25)
                          Recheck Cond: geohash_zone = ANY ('{9q8yyk,...}')
                          Filter: status='online' AND st_dwithin(location, $point, 5000)
                          ->  BitmapAnd
                                ->  Bitmap Index Scan on ix_drivers_geohash_zone
                                ->  Bitmap Index Scan on idx_drivers_location
                                      Index Cond: location && _st_expand($point, 5000)
            Planning Time: 0.670 ms
            Execution Time: 5.878 ms

        Both indexes are combined (BitmapAnd): the btree geohash pre-filter and
        the GiST spatial index. Regenerate with scripts/explain_matching.py.
        """
        # Build the reference point as a geography so distances are in metres.
        ref = cast(func.ST_SetSRID(func.ST_MakePoint(lng, lat), 4326), Geography)
        stmt = (
            select(Driver)
            .where(
                Driver.status == DriverStatus.online,
                Driver.location.isnot(None),
                func.ST_DWithin(Driver.location, ref, radius_m),
            )
            .order_by(func.ST_Distance(Driver.location, ref))
            .limit(1)
        )
        if zones:
            stmt = stmt.where(Driver.geohash_zone.in_(zones))
        result = await self.db.execute(stmt)
        return result.scalar_one_or_none()

    async def set_location(
        self,
        driver: Driver,
        *,
        lat: float,
        lng: float,
        geohash_zone: str,
        updated_at: datetime,
    ) -> Driver:
        # WKT/PostGIS coordinate order is (lng lat). The geography column drives
        # spatial queries; the float mirrors keep responses cheap.
        driver.location = WKTElement(f"POINT({lng} {lat})", srid=4326)
        driver.current_lat = lat
        driver.current_lng = lng
        driver.geohash_zone = geohash_zone
        driver.last_location_update = updated_at
        await self.db.flush()
        return driver
